### ISSUE TITLE
feat002-member

### ISSUE THREAD

**Issue by wooseong-choi** [Jungle-Team3-Olympus/jungle-navigation-react#1]
### ✨ Describe

JWT를 통한
회원 가입
로그인
구글 소셜 로그인
NEST REST API 서버와 WS 통신하여 캐릭터 정보 동기화 (위치 등)

### ✅ Tasks

- [x] JWT를 통한
- [x] 회원 가입
- [x] 로그인
- [x] 구글 소셜 로그인
- [x] NEST REST API 서버와 WS 통신하여 캐릭터 정보 동기화 (위치 등)

### 🕰️ Estimated Time of Completion

4일

**Comment by Digit24-dev** [comment]
Done

**Comment by wooseong-choi** [comment]
굿굿
